### ISSUE TITLE
Improve existing datasets

### ISSUE THREAD

**Issue by brehaut** [brehaut/manticore#37]
Once Issue #35 is complete the existing datasets can be improved in two ways:

- [ ] Support for `weakling` for any monster in _13 True Ways_ that may have been erroneously missed.
- [ ] Refine monsters that are listed as `large` or `huge` but are more accurately described as `double` or `triple` strength.

**Comment by NightB1ade** [comment]
Does the code support "double" or "triple" as monster "sizes" at the moment?  On my edits yesterday, I didn't change those just yet cos I thought the code might not support it yet.  But if it does, I'll refine those in the next edit and include that in the next pull request.

**Comment by brehaut** [comment]
I believe so. 

The terms are actually `double strength` and `triple strength` by the looks of the code

There are two places to check to see these rules.

First is https://github.com/brehaut/manticore/blob/master/src/ts/common/data.ts#L23-L43 which converts the somewhat human manageable JSON format into the internal representation that manticore uses. Notably this normalises a number of terms because their impact on manticore is only to do with the costing calculation so we don’t currently need all the extra detail internally.

Secondly, if you look at https://github.com/brehaut/manticore/blob/master/src/ts/common/costs.ts#L31-L71 you'll see all the rules that are applied to the cost of a monster.

**Comment by brehaut** [comment]
As a sideline second point, looking at the lines in `costs.ts` I mentioned, I think the rules around costing weaklings and elites needs to be revisited. I think its working correctly but the code is nasty: it looks like it should apply the modifier twice for those (once as threat, and once as size). But the data normalisation functions are actually stripping weakling and elite out of one of `size` and `threat`

**Comment by NightB1ade** [comment]
![Building Battles](https://user-images.githubusercontent.com/18259801/147372012-b44cae3b-b329-4871-931e-e445e74caf9c.png)
From Bestiary 2.

I think it's right that it's only applying the elite and weakling once.  And due to the stripping of it out of `size` on normalising, it's works as the rules intend.  And the few examples of `large elite` mean that the `large` and `elite` are parsed separately.

The code could be cleaned up to remove https://github.com/brehaut/manticore/blob/master/src/ts/common/costs.ts#L41-L46 for clarity.

---

Where I think it doesn't work as it stands is `weakling mooks`.  They aren't parsed separately and combined as per the second table.

---

Otherwise, ideally (as the Data Architect in me), I'd want to separate the size and threat into two different parts in the JSON.

On a separate thought, I'll probably do that in the thing I'm working on, maybe once I've finished (I'll add in page numbers as I go, and consider how to add the extra tags in), that will mean that potentially could switch over data sources (or clean/minimise it to incorporate into manticore) such that they run off the same dataset and can cross reference?
