### ISSUE TITLE
Error on first compilation

### ISSUE THREAD

**Issue by Cousken** [brehaut/manticore#41]
Hello!

I had an idea about adding some options to encounter generation to make it easier to find what i want and make the resulting list smaller. Things like "include at least 1 soldier, 1 leader and no more than 4 mooks". Instead of suggesting it, i decided to try an implement it, even tho i'm a desktop application dev and don't know nodejs or java/typescript that well.

Anyway, i made myself an ubuntu installation in a virtual box and set up node, npm, gulp etc. **TL;DR** First time compiling the code i got this error message: 
```
`src/ts/app/manticore.ts(61,9): error TS2345: Argument of type '(party: IParty, monsters: Monster[]) => Promise<{}>' is not assignable to parameter of type 'Allocator'.
  Type 'Promise<{}>' is not assignable to type 'Promise<Allocation[][][]>'.
    Type '{}' is not assignable to type 'Allocation[][][]'.
      Property 'length' is missing in type '{}'.
```

```
/home/cousken/git/manticore/src/ts/vendor/react/react.d.ts(162,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
[21:29:37] TypeScript: 2 semantic errors
[21:29:37] TypeScript: emit succeeded (with errors)
```

```
/home/cousken/git/manticore/src/ts/workers/data-access/dataset.ts(34,27): error TS2345: Argument of type '(_: any) => Promise<string>' is not assignable to parameter of type '((reason: any) => PromiseLike<never>) | null | undefined'.
  Type '(_: any) => Promise<string>' is not assignable to type '(reason: any) => PromiseLike<never>'.
    Type 'Promise<string>' is not assignable to type 'PromiseLike<never>'.
      Types of property 'then' are incompatible.
        Type '<TResult1 = string, TResult2 = never>(onfulfilled?: ((value: string) => TResult1 | PromiseLike<TR...' is not assignable to type '<TResult1 = never, TResult2 = never>(onfulfilled?: ((value: never) => TResult1 | PromiseLike<TRes...'.
          Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'string' is not assignable to type 'never'.
```
`

The website works fine however. So i'm just letting you know.

**Comment by brehaut** [comment]
Hi, thanks for raising this issue.

### The error
It looks like if you follow the instructions in the readme and use `npm install` it does bomb out; I suspect its pulling in the wrong typescript version or something. NPM is a pain. I'll update the readme to suggest using facebook's [yarn](https://yarnpkg.com/en/) frontend (which is what I am actually using) and you should have no trouble building. Welcome to the merry world of javascript tools I guess.

### Bounding generation by type
The feature you mention is something I have been wanting to look at implementing. There are a couple of issues related to it: #30, #25. In a nutshell this involves improving the allocator algorithm replacing the special cased territorial monster support with something more general. It's sat on the sidelines so far due as I was waiting for viable support for generators in javascript/typescript which I only adopted recently. 

### Development environment
While you are welcome to use virtual box if you wish, there is nothing about this project that should require it. I build it primarily on macOS but I also build and test it on windows 10 regularly. Typescript being a Microsoft project is a very good citizen on windows. I'd also recommend Visual Studio Code as an editor for typescript if you haven't any other strong priorities, as it has excellent integration with the language service and I already have checked in the relevant configuration for the project.

Just one final note: this project is something of a playground for exploring ideas for me. It's always a little in flux and may contain some wacky things from time to time.

**Comment by Cousken** [comment]
Thank you so much for taking your time to write such an informative reply :)

Your new read me does indeed guide me to a successful compilation. From what you are saying it does sound like the issue is bigger than i thought and maybe not something a newbie like me will be able to solve, but i can give it a go, at least.

As for the virtual box, i find that web development tools often depend on tools which are just easier done via a terminal, and Linux just seems better at that. I also don't want to install a bunch of stuff on my main machine because i want to play around with a project, a Virtual box is very easy to dump. Visual Studio Code i think is available on Linux, but i will miss my Visual Studio Pro...

**Comment by brehaut** [comment]
Not a problem. Have a look at issue #25, I've made a couple of notes there and linked to the specific parts of the allocation algorithm that will need to change. I don't think this is an insurmountable task to get started with. 

To start with I think that the best thing to do would be to begin by replacing the existing special cased rules with one datastructure that can track all that information, and thread it through the code. This means you can get the infrastructure in place without having to change the UI at all. 

It's probably worth also extending the test properties to cover these rules more precisely. 

You'll probably want to familiarise yourself with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators. The short version is that they are equivalent to Enumerators in DotNet:
 * Iterable<T> is similar to IEnumerable<T>, Iterator<T> is similar to IEnumerator<T>. There is an additional interface IterableIterator<T> in javascript / typescript that does basically what it says on the tin. It's the return type of generator functions too.
 * Generators are special functions that can use the `yield` statement. This is equivalent to `yield return` in C#. Unlike C# you need to declare a function as being a generator with the special syntax `function*` (and use the appropriate return type).
 * `yield*` takes an enumerable on the right hand side, and yields each item one by one. Think of it as a flattening `yield`. 

There's a couple of other things you'll have to get the hang of with this too: the allocation algorithm runs inside a web worker. A new worker is spawned for each click of the generate button. The chrome dev tools have a good debugger here, but you may find that the javascript / typescript keyword `debugger` will be extremely useful: It's an easy way to trip the debugger to pause in the web worker context so that you can set up your actual breakpoints in the debugger.  The developer tools will give you some visibility into the appcache machinery too; it's a giant pain unfortunately; where possible running the relevant test prop you care about is easier.

**Comment by brehaut** [comment]
It would probably be remiss of me to mention that this project has 'just enough infrastructure' to get things done; I don't enjoying faffing about with the wild world of javascript tools. If you have any questions about the madness that does exist just let me know. The gulpfile defines all the targets. 

### Some notes on the test suite:
You probably also want to install the [`mocha`](http://mochajs.org/) test tool via npm. That will let you run the tests. I'll update the readme when i have a moment.  I'm actually writing the tests using [JSVerify](https://github.com/jsverify/jsverify) which is a property testing library. If you have experience with FSCheck on DotNet its a similar idea. If you haven't you notice that the properties under test are more general than what you might see in a typical unit testing library. 

A minor point: the tests are written in javascript so you wont get type checking. Basically just because it simplifies the infrastructure.
